

export const sample_product: any[] = [
 {"product_id":'44', "description":"Warrious Chair WGC206 Series ", "image":"assets/images/gaming1.png", "price":1916.0, "product_name":"Gaming 1", "quantity":150, "category_na":"Gaming room"},
 {"product_id":'47', "description":"Gaming Board G1", "image":"assets/images/gaming2.png", "price":67.0, "product_name":"Gaming 2", "quantity":55, "category_na":"Gaming room"},
 {"product_id":'48', "description":"Sofa set BSF166", "image":"assets/images/living1.png", "price":1001.0, "product_name":"Living 1", "quantity":52, "category_na":"Living room"},
 {"product_id":'49', "description":"TV shelf KTV8917", "image":"assets/images/living2.png", "price":984.0, "product_name":"Living 2", "quantity":50, "category_na":"Living room"},
 {"product_id":'50', "description":"Decorative table BC017", "image":"assets/images/living3.png", "price":1100.0, "product_name":"Living 3", "quantity":99, "category_na":"Living room"},
 {"product_id":'51', "description":"Kitchen Card A02", "image":"assets/images/kit1.png", "price":847.0, "product_name":"Kitchen 1", "quantity":20, "category_na":"Kitchen"},
 {"product_id":'52', "description":"Acrylic-A010 Kitchen Cabinet", "image":"assets/images/kit2.png", "price":810.0, "product_name":"Kitchen 2", "quantity":45, "category_na":"Kitchen"},
 {"product_id":'53', "description":"Kitchen Card A03", "image":"assets/images/kit3.png", "price":874.0, "product_name":"Kitchen 3", "quantity":67, "category_na":"Kitchen"},
 {"product_id":'54', "description":"Acrylic-A14 Kitchen Cabinet", "image":"assets/images/kit4.png", "price":947.0, "product_name":"Kitchen 4", "quantity":13, "category_na":"Kitchen"},
 {"product_id":'55', "description":"Sofa GSF 127", "image":"assets/images/living4.png", "price":893.0, "product_name":"Living 4", "quantity":67, "category_na":"Living room"},
 {"product_id":'56', "description":"Sofa set BSF1001", "image":"assets/images/living5.png", "price":1038.0, "product_name":"Living 5", "quantity":76, "category_na":"Living room"},
 {"product_id":'57', "description":"Sofa set BSF614", "image":"assets/images/living6.png", "price":983.0, "product_name":"Living 6", "quantity":98, "category_na":"Living room"},
 {"product_id":'58', "description":"High End PC I9-11900K RTX-3090", "image":"assets/images/gaming3.png", "price":10905.0, "product_name":"Gaming 3", "quantity":35, "category_na":"Gaming room"},
 {"product_id":'59', "description":"Acrylic-A15 Kitchen Cabinet", "image":"assets/images/kit5.png", "price":970.0, "product_name":"Kitchen 5", "quantity":65, "category_na":"Kitchen"},
 {"product_id":'60', "description":"Acrylic-A017 Kitchen Cabinet", "image":"assets/images/kit6.png", "price":985.0, "product_name":"Kitchen 6", "quantity":23, "category_na":"Kitchen"},
 {"product_id":'61', "description":"Sofa set BSF121", "image":"assets/images/living7.png", "price":859.0, "product_name":"Living 7", "quantity":31, "category_na":"Living room"},
 {"product_id":'62', "description":"Acrylic-A018 Kitchen Cabinet", "image":"assets/images/kit7.png", "price":979.0, "product_name":"Kitchen 7", "quantity":84, "category_na":"Kitchen"},
 {"product_id":'63', "description":"Acrylic-A019 Kitchen Cabinet", "image":"assets/images/kit8.png", "price":979.0, "product_name":"Kitchen 8", "quantity":67, "category_na":"Kitchen"},
 {"product_id":'64', "description":"Acrylic-A020 Kitchen Cabinet", "image":"assets/images/kit9.png", "price":989.0, "product_name":"Kitchen 9", "quantity":62, "category_na":"Kitchen"},
 {"product_id":'65', "description":"Acrylic-A022 Kitchen Cabinet", "image":"assets/images/kit10.png", "price":969.0, "product_name":"Kitchen 10", "quantity":52, "category_na":"Kitchen"},
 {"product_id":'66', "description":"Sofa set BSF029", "image":"assets/images/living8.png", "price":869.0, "product_name":"Living 8", "quantity":35, "category_na":"Living room"},
 {"product_id":'67', "description":"Sofa set BSF028", "image":"assets/images/living9.png", "price":859.0, "product_name":"Living 9", "quantity":15, "category_na":"Living room"},
 {"product_id":'68', "description":"Sofa set BSF027", "image":"assets/images/living10.png", "price":865.0, "product_name":"Living 10", "quantity":53, "category_na":"Living room"},
 {"product_id":'69', "description":"TV shelf KTV010", "image":"assets/images/living11.png", "price":869.0, "product_name":"Living 11", "quantity":79, "category_na":"Living room"},
 {"product_id":'70', "description":"Shoe Cabinet TGGCN", "image":"assets/images/living12.png", "price":860.0, "product_name":"Living 12", "quantity":65, "category_na":"Living room"},
 {"product_id":'71', "description":"PS5 Standard Edition - KOREA", "image":"assets/images/gaming4.png", "price":653.0, "product_name":"Gaming 4", "quantity":143, "category_na":"Gaming room"},
 {"product_id":'72', "description":"Game Disc Holder", "image":"assets/images/gaming5.png", "price":278.0, "product_name":"Gaming 5", "quantity":147, "category_na":"Gaming room"},
 {"product_id":'73', "description":"Display Cabinet TTB02", "image":"assets/images/gaming6.png", "price":360.0, "product_name":"Gaming 6", "quantity":143, "category_na":"Gaming room"},
 {"product_id":'74', "description":"Bauhutte gaming bed set", "image":"assets/images/gaming7.png", "price":665.0, "product_name":"Gaming 7", "quantity":96, "category_na":"Gaming room"},
 {"product_id":'75', "description":"Full PC Gaming Yasuo", "image":"assets/images/gaming8.png", "price":10060.0, "product_name":"Gaming 8", "quantity":43, "category_na":"Gaming room"},
 {"product_id":'77', "description":"Classic laundry room", "image":"assets/images/la1.png", "price":959.0, "product_name":"Laundry 1", "quantity":34, "category_na":"Laundry room"},
 {"product_id":'78', "description":"Laundry room for fashionistas", "image":"assets/images/la2.png", "price":956.0, "product_name":"Laundry 2", "quantity":83, "category_na":"Laundry room"},
 {"product_id":'79', "description":"Traditional laundry room", "image":"assets/images/la3.png", "price":945.0, "product_name":"Laundry 3", "quantity":73, "category_na":"Laundry room"},
 {"product_id":'80', "description":"Bright white laundry room", "image":"assets/images/la4.png", "price":949.0, "product_name":"Laundry 4", "quantity":48, "category_na":"Laundry room"},
 {"product_id":'81', "description":"Luxurious laundry room, lavish", "image":"assets/images/la5.png", "price":978.0, "product_name":"Laundry 5", "quantity":34, "category_na":"Laundry room"},
 {"product_id":'82', "description":"Stylish laundry room", "image":"assets/images/la6.png", "price":950.0, "product_name":"Laundry 6", "quantity":82, "category_na":"Laundry room"},
 {"product_id":'83', "description":"Themed laundry room", "image":"assets/images/la7.png", "price":950.0, "product_name":"Laundry 7", "quantity":63, "category_na":"Laundry room"},
 {"product_id":'84', "description":"Spacious laundry room", "image":"assets/images/la8.png", "price":955.0, "product_name":"Laundry 8", "quantity":28, "category_na":"Laundry room"},
 {"product_id":'85', "description":"Laundry room with curtains", "image":"assets/images/la9.png", "price":949.0, "product_name":"Laundry 9", "quantity":21, "category_na":"Laundry room"},
 {"product_id":'86', "description":"Pink laundry room", "image":"assets/images/la10.png", "price":959.0, "product_name":"Laundry 10", "quantity":445, "category_na":"Laundry room"},
 {"product_id":'87', "description":"Modern bright laundry room", "image":"assets/images/la11.png", "price":960.0, "product_name":"Laundry 11", "quantity":62, "category_na":"Laundry room"},
 {"product_id":'88', "description":"Bathtub - AT0950", "image":"assets/images/ba1.png", "price":278.0, "product_name":"Bath 1", "quantity":265, "category_na":"Bathroom"},
 {"product_id":'89', "description":"Bibs Bathtub - AT0440L/CHEAP", "image":"assets/images/ba2.png", "price":360.0, "product_name":"Bath 2", "quantity":152, "category_na":"Bathroom"},
 {"product_id":'90', "description":"Two-piece Toilet with Soft Lid - CD1340", "image":"assets/images/ba3.png", "price":245.0, "product_name":"Bath 3", "quantity":293, "category_na":"Bathroom"},
 {"product_id":'91', "description":"Hand Dryer - A610", "image":"assets/images/ba4.png", "price":150.0, "product_name":"Bath 4", "quantity":546, "category_na":"Bathroom"},
 {"product_id":'92', "description":"Hot and Cold Shower - S173C", "image":"assets/images/ba5.png", "price":250.0, "product_name":"Bath 5", "quantity":834, "category_na":"Bathroom"},
 {"product_id":'93', "description":"Mens urinal (Wall-mounted) - U0232", "image":"assets/images/ba6.png", "price":159.0, "product_name":"Bath 6", "quantity":453, "category_na":"Bathroom"},
 {"product_id":'94', "description":"Bedroom furniture 1914", "image":"assets/images/bed1.png", "price":1916.0, "product_name":"Bed 1", "quantity":56, "category_na":"Bedroom"},
 {"product_id":'95', "description":"High-class bedroom furniture 1924", "image":"assets/images/bed2.png", "price":1904.0, "product_name":"Bed 2", "quantity":38, "category_na":"Bedroom"},
 {"product_id":'96', "description":"High-class bed and wardrobe set 1816", "image":"assets/images/bed3.png", "price":1856.0, "product_name":"Bed 3", "quantity":82, "category_na":"Bedroom"},
 {"product_id":'97', "description":"Imported high-class bed and cabinet set 2196", "image":"assets/images/bed4.png", "price":1703.0, "product_name":"Bed 4", "quantity":13, "category_na":"Bedroom"},
 {"product_id":'98', "description":"Cream white bed set 1826", "image":"assets/images/bed5.png", "price":1744.0, "product_name":"Bed 5", "quantity":73, "category_na":"Bedroom"},
 {"product_id":'99', "description":"Full set of high-class beds and cabinets 1895", "image":"assets/images/bed6.png", "price":1912.0, "product_name":"Bed 6", "quantity":37, "category_na":"Bedroom"},
 {"product_id":'100', "description":"Bed and cabinet design 1828", "image":"assets/images/bed7.png", "price":1690.0, "product_name":"Bed 7", "quantity":58, "category_na":"Bedroom"},
 {"product_id":'101', "description":"Cheap luxury bed and wardrobe 1996", "image":"assets/images/bed8.png", "price":1729.0, "product_name":"Bed 8", "quantity":35, "category_na":"Bedroom"},
 {"product_id":'107', "description":"Taiwan 1815 bed and cabinet set", "image":"assets/images/bed9.png", "price":1855.0, "product_name":"Bed 9", "quantity":20, "category_na":"Bedroom"}
]

export const sample_category:any[] = [
 {"category_name":"Gaming room", "count":8},
 {"category_name":"Bedroom", "count":9},
 {"category_name":"Bathroom", "count":6},
 {"category_name":"Living room", "count":12},
 {"category_name":"Kitchen", "count":9},
 {"category_name":"Laundry room", "count":11}
]